version: '3.8'

services:
  # Base de données PostgreSQL
  database:
    image: postgres:15-alpine
    container_name: password_manager_db
    environment:
      POSTGRES_DB: password_manager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secure_password_2024
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - password_manager_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d password_manager"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend Flask
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: password_manager_backend
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://admin:secure_password_2024@database:5432/password_manager
      - JWT_SECRET_KEY=your_jwt_secret_key_change_in_production
      - ENCRYPTION_KEY=your_32_byte_encryption_key_change_me
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      database:
        condition: service_healthy
    networks:
      - password_manager_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: password_manager_frontend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - password_manager_network

networks:
  password_manager_network:
    driver: bridge

volumes:
  postgres_data: